# Generated by Django 5.0.1 on 2024-03-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_agree',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_test_device',
            field=models.BooleanField(default=False),
        ),
    ]
