# Generated by Django 5.0.1 on 2024-02-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_remove_notification_device_notification_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='college',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='department',
        ),
        migrations.RemoveField(
            model_name='device',
            name='setting',
        ),
        migrations.DeleteModel(
            name='HomeSet',
        ),
        migrations.DeleteModel(
            name='BasicSet',
        ),
        migrations.DeleteModel(
            name='CollegeSet',
        ),
        migrations.DeleteModel(
            name='DepartmentSet',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
