# Generated by Django 5.0.1 on 2024-03-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_device_is_agree_device_is_test_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_iOS',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
