# Generated by Django 5.0.1 on 2024-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineering',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='softwareengineering',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
