# Generated by Django 5.0.1 on 2024-04-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_device_is_ios_device_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
