# Generated by Django 5.0.1 on 2024-04-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0005_alter_question_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ios_latest_version', models.CharField(default='0.0.0', max_length=10)),
                ('aos_latest_version', models.CharField(default='0.0.0', max_length=10)),
            ],
        ),
    ]
