# Generated by Django 5.0.1 on 2024-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0005_businesspost_alter_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspost',
            name='link',
            field=models.URLField(default='https://naver.com'),
            preserve_default=False,
        ),
    ]
