# Generated by Django 5.0.1 on 2024-02-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0005_engineering_num_softwareengineering_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering',
            name='num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='softwareengineering',
            name='num',
            field=models.PositiveIntegerField(),
        ),
    ]
