# Generated by Django 5.0.1 on 2024-07-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0006_appinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
