# Generated by Django 5.0.1 on 2024-02-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0006_businesspost_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegepost',
            name='link',
            field=models.URLField(default='https://naver.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentpost',
            name='link',
            field=models.URLField(default='https://naver.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepost',
            name='link',
            field=models.URLField(default='https://naver.com'),
            preserve_default=False,
        ),
    ]
