# Generated by Django 5.0.1 on 2024-02-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0007_collegepost_link_departmentpost_link_homepost_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
