# Generated by Django 5.0.1 on 2024-02-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0007_architecture_department_architecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsEngineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
