# Generated by Django 5.0.1 on 2024-02-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0008_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
