# Generated by Django 5.0.1 on 2024-02-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0008_materialsengineering'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='materials_engineering',
            field=models.BooleanField(default=False),
        ),
    ]
