# Generated by Django 5.0.1 on 2024-01-31 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_remove_user_id_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alarm.setting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(unique=True),
        ),
    ]
