# Generated by Django 5.0.1 on 2024-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_user_setting_alter_user_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=99, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
