# Generated by Django 5.0.1 on 2024-07-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('direction_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
