# Generated by Django 5.0.1 on 2024-12-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bannerad_is_external_browser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBannerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField()),
                ('direction_url', models.URLField(blank=True)),
                ('expiry_date', models.DateField()),
                ('is_external_browser', models.BooleanField(default=False)),
                ('is_available', models.BooleanField()),
            ],
        ),
    ]
